- Build additional queries on top of the results of the `GROUPING SETS` aggregations above to answer the following questions:
  - Write a query (`query_4`) to answer: "Which player scored the most points in one season?"
